#ifndef PULSE433_TYPES_H
#define PULSE433_TYPES_H

#ifdef __UINT8_TYPE__
#define PULSE433_SIZE_T __UINT8_TYPE__
#define PULSE433_BYTE_T __UINT8_TYPE__
#else
#define PULSE433_SIZE_T unsigned char
#define PULSE433_BYTE_T unsigned char
#endif

#ifdef __CHAR_BIT__
#define PULSE433_BITS_PER_BYTE __CHAR_BIT__
#else
#define PULSE433_BITS_PER_BYTE 8
#endif

#define PULSE433_TRANSMITTER_BUFF_MAX_SIZE 32
#define PULSE433_TRANSMITTER_TICKS_PER_SHORT_PULSE 1
#define PULSE433_TRANSMITTER_TICKS_PER_LONG_PULSE 4
#define PULSE433_TRANSMITTER_TICKS_PER_START_PULSE 8


#endif
